### ISSUE TITLE
PROPOSAL - Jump to Post

### ISSUE THREAD

**Issue by DrSAR** [Amonith/mattermost-file-list#15]
It would be nice to be able to jump to a post that's related to a particular attachement. This could be similar in appearance to the 'Jump' link that's provided by the SEARCH RESULTS when performing a search.

**Comment by Amonith** [comment]
Hi,
Good suggestion. Implemented in the latest release:
https://github.com/Amonith/mattermost-file-list/releases/tag/v0.6.0
