### ISSUE TITLE
PROPOSAL: Make search by file name case insensitive

### ISSUE THREAD

**Issue by dantepippi** [Amonith/mattermost-file-list#17]
Greetings and thanks for the plugin, it's quite usefull!

It would be nice to have the ability to search by file name without worrying with lower/upper case.

**Comment by Amonith** [comment]
Can do, but it will be an opt-in feature (admin will have turn it on in plugin settings).
The name column is not indexed in MM database so this will result in performance degradation in larger organizations (like the one I'm currently in where there are thousands of files).

**Comment by Amonith** [comment]
Actually it was case-insensitive from the beginning 😅 
Anyway, added an additional option for this in the latest release:
https://github.com/Amonith/mattermost-file-list/releases/tag/v0.9.0
