### ISSUE TITLE
Plugin Security

### ISSUE THREAD

**Issue by gardinermichael** [Amonith/mattermost-file-list#19]
Hello,

I was hoping to install your plugin for my team but I was wondering about the security implications. I'm not too familiar with Go, otherwise I would look for myself, but I was wondering about SQL Injections and potentially open API routes. 

Thank you
Michael

**Comment by Amonith** [comment]
Hi,

Technically there's only a single endpoint managed by Mattermost. And on that single endpoint the first thing I do is make sure that there is a logged in user:

https://github.com/Amonith/mattermost-file-list/blob/master/server/plugin.go#L44

Mattermost handles user auth entirely, I just need to check for the existence of that server-side header (can't be spoofed by the client when making a request).

About SQL Injection, well, you can verify the code here:
https://github.com/Amonith/mattermost-file-list/blob/master/server/services/db_service.go

but I had it in mind when writing the code and made sure that it is not vulnerable (I use SQL parameters on everything passed from outside).

**Comment by gardinermichael** [comment]
Brilliant, I appreciate your response!

The plugin is great. Thank you for taking the time to develop it.

**Comment by Amonith** [comment]
The pleasure is mine :)
More features are planned and will come in the future.
