### ISSUE TITLE
Database schema warning on Mattermost 5.22.0

### ISSUE THREAD

**Issue by emi80** [Amonith/mattermost-file-list#29]
Hi @Amonith 

I am having an issue with the file-list plugin on Mattermost 5.22.0. The plugins installs and seems to load fin. The channel files list is shown, but when I click on a file I get a `404` error from the server. I am getting the following message in my server logs:
```
{"level":"info","ts":1589445730.3519459,"caller":"go-plugin@v1.0.1/stream.go:15","msg":"{\"level\":\"warn\",\"msg\":\"The database schema with version 5.22.0 is newer than Mattermost version 5.16.0.\"}","plugin_id":"mattermost-file-list","source":"plugin_stdout"}
```

I guess my issue might be related to that. Could you please have a look?

Thanks a lot,
Emilio

**Comment by emi80** [comment]
I think the `404` issue probably not related. It seems an issue with the `Site URL1

**Comment by emi80** [comment]
Just for your information, the problem is that my Site URL is hosted on a subpath `/mm` and the fetched URL of files and thumbnails does not contain the subpath but only the base URI.

Let me know if you want me to open an other issue for this.

Best

**Comment by Amonith** [comment]
Hi,
Closing the issue as we solved this in other tickets.
