### ISSUE TITLE
Wrong URLs returned if Mattermost instance is hosted at a subpath 

### ISSUE THREAD

**Issue by emi80** [Amonith/mattermost-file-list#30]
Hi,

we are hosting out Mattermost instance at a subpath and installed the `file-list` plugin `version 0.8.1`. The plugin always returns URLs without the subpath for files, thumbnails and file post locations.

**Comment by Amonith** [comment]
Hey, thanks. I merged your PR, looks good enough for me :)

Included in the latest release:
https://github.com/Amonith/mattermost-file-list/releases/tag/v0.9.0
