### ISSUE TITLE
Space between team name and channels in the sidebar

### ISSUE THREAD

**Issue by YuKitAs** [Amonith/mattermost-file-list#33]
After disabling the file list for admins, there will be a 10px margin left at the top of the sidebar (see screenshot).
![mattermost](https://user-images.githubusercontent.com/9809206/83336583-ff582080-a2b4-11ea-8891-f47e0fb98857.png)

**Comment by Amonith** [comment]
Thanks, fixed in release 0.9.0:
https://github.com/Amonith/mattermost-file-list/releases/tag/v0.9.0
