### ISSUE TITLE
can delete files I shouldn't be able to delete

### ISSUE THREAD

**Issue by bbodenmiller** [Amonith/mattermost-file-list#39]
It appears I'm able to delete other peoples files. That doesn't sound like expected behavior.

**Comment by Amonith** [comment]
That depends. Are you a system or channel admin? Because if you can edit other people's messages you will also be able to do this through the plugin.

**Comment by bbodenmiller** [comment]
In this case I was running as team admin but my settings are set to not allow team admins to edit or delete others posts...
