### ISSUE TITLE
Disable "Copy Link" Action when FileSettings.EnablePublicLink=false

### ISSUE THREAD

**Issue by ali-farooq0** [Amonith/mattermost-file-list#8]
Just ran into an issue where when clicking "Copy Link" Action whilst `FileSettings.EnablePublicLink=false` the plugin doesn't do anything, provides no visual feedback that it failed to copy the link.

Steps to reproduce:
1. Set `FileSettings.EnablePublicLink=false`
2. Click "Files in channel" button
3. Make sure the list contains at least one file
4. Click "Copy Link" action

Observed:
Link is not copied, and no visual feedback is provided that it wasn't copied. Error is seen in the developer console.

Expected:
Either show an error dialog to inform the user that the `FileSettings.EnablePublicLink` option is disabled or disable the "Copy Link" action in that case.

**Comment by Amonith** [comment]
Hi,
Thank you for the report.
I've tried to experiment with those redux actions for success/error messages:
https://github.com/mattermost/mattermost-redux/blob/master/src/actions/alerts.ts

but had no luck with those yet.
I'll implement something different in the upcoming days.

**Comment by ali-farooq0** [comment]
@Amonith yeah doesn't look like we use that in the webapp at all. Sigh. We use https://github.com/mattermost/mattermost-webapp/blob/2dd0ffeb3a7d3ae68ea303f30394ca7eacf2ddd9/components/announcement_bar/announcement_bar.jsx#L11. Which isn't available to Plugins.

Your best bet would be to use the bootstrap Modal component.

**Comment by ali-farooq0** [comment]
Other option could be to just disable the `Copy Link` button when public links are disabled.

**Comment by Amonith** [comment]
This check has been added in the latest release:
https://github.com/Amonith/mattermost-file-list/releases/tag/v0.7.0
